name: CI/CD - Lint + Build + Push

on:
  push:
    branches: [ "feat/CICD" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          #
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 
      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Fix
        run: ruff check --fix .

      # 
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix linting errors [skip ci]"

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install pytest-django httpx
            pip install -r api/requirements-dev.txt
            pip install -r django_political_app/requirements-dev.txt

      - name: Set environment variables
        run: |
            echo "DJANGO_SETTINGS_MODULE=django_political_app.settings" >> $GITHUB_ENV
            echo "SECRET_KEY=test-secret-key" >> $GITHUB_ENV      

      - name: Run tests
        run: pytest

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push FastAPI
        run: |
          docker build -t ghcr.io/edilenesilva/fastapi-app:v1.0 ./api
          docker push ghcr.io/edilenesilva/fastapi-app:v1.0

      - name: Build and push Django
        run: |
          docker build -t ghcr.io/edilenesilva/django-app:v1.0 ./django_political_app
          docker push ghcr.io/edilenesilva/django-app:v1.0

      - name: Build and push Ingest
        run: |
          docker build -t ghcr.io/edilenesilva/ingest-app:v1.0 -f scripts/Dockerfile .
          docker push ghcr.io/edilenesilva/ingest-app:v1.0